<a href="https://colab.research.google.com/github/036takashima/pandas-kindle/blob/main/PandasSpeed.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive 
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive


In [ ]:
# file = pd.read_csv('/content/drive/MyDrive/ColabNotebooks/pandas-kindle/test_r.csv')

color      director_name  ...  aspect_ratio  movie_facebook_likes
0  Color      James Cameron  ...          1.78                 33000
1  Color     Gore Verbinski  ...          2.35                     0
2  Color         Sam Mendes  ...          2.35                 85000
3  Color  Christopher Nolan  ...          2.35                164000
4    NaN        Doug Walker  ...           NaN                     0

[5 rows x 28 columns]

In [2]:
import csv
with open("/content/drive/MyDrive/ColabNotebooks/pandas-kindle/test_r.csv", mode="r", encoding="utf-8") as fp:
  # Readerを取得
  csv_reader = csv.reader(fp)
  # ループで行ごとにリストで取得できます
  for row in csv_reader:
    print(row)

['1', '2', '3']
['4', '5', '6']
['7', '8', '9']


In [4]:
import csv 
header = ["A", "B", "C"] 
data = [[1, 2, 3],
        [ 4, 5, 6],
        [ 7, 8, 9]] 
with open("/content/drive/MyDrive/ColabNotebooks/pandas-kindle/test_w.csv", mode = "w", encoding = "utf-8") as fp: 
  csv_writer = csv.writer(fp, lineterminator ="\n") 
  csv_writer.writerow(header)
  csv_writer.writerows(data)

## numpy

In [9]:
import numpy as np
num_list = [1, 2, 3, 4, 5]
print(num_list)
nd_ary = np.asarray(num_list)
print(type(nd_ary))
print(nd_ary)
for i in nd_ary:
  print(i)

[1, 2, 3, 4, 5]
<class 'numpy.ndarray'>
[1 2 3 4 5]
1
2
3
4
5


In [10]:
import numpy as np
num_list = [[1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]]
nd_ary = np.asarray(num_list)
print(nd_ary)
for i in nd_ary:
  print(i)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[4 5 6]
[7 8 9]


In [11]:
import numpy as np
num_list = [[1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]]
nd_ary = np.asarray(num_list)
print(type(nd_ary))
print(nd_ary)
# ndarray→リスト
to_list = nd_ary.tolist()
print(type(to_list))
print(to_list)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'list'>
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [13]:
import numpy as np
num_list = [[1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]]
print(np.asarray(num_list,dtype=np.int64))
print(np.asarray(num_list,dtype=np.int64).tolist())
print(np.asarray(num_list,dtype=np.float64))         
print(np.asarray(num_list,dtype=np.float64).tolist())         

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]


In [14]:
import numpy as np
num_list = [[1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]]
nd_ary_float64 = np.asarray(num_list, dtype=np.float64)
nd_ary_int64 = nd_ary_float64.astype(np.int64)
print(nd_ary_float64)
print(nd_ary_int64)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 配列初期化関数